In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000, n_features=3, n_redundant=0, n_classes=2, random_state=1)

In [5]:
X

array([[ 0.60500791,  0.51340375, -1.55859419],
       [ 0.81846819, -1.88473945,  1.49992516],
       [ 0.53437474, -0.01420736,  0.2771265 ],
       ...,
       [ 2.28830983,  3.74857955, -0.5886461 ],
       [-0.28103796, -1.84729902,  1.13548397],
       [ 0.76642645, -1.29293146,  0.88279907]])

In [7]:
y

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,

In [9]:
from sklearn.model_selection import train_test_split
X_test,X_train,y_test,y_train =train_test_split(X, y, test_size=0.3, random_state=1)

In [11]:
X_test

array([[ 0.13696193,  0.67815108, -0.14461932],
       [ 0.57366538, -1.25590314,  0.34284631],
       [-1.87258854,  1.20568569,  0.11236385],
       ...,
       [ 0.62279308, -1.56698137,  0.65941881],
       [ 1.02164878, -0.10923548, -1.20447744],
       [-1.5870461 , -2.72691664, -0.23260288]])

In [13]:
X_train

array([[-6.21513636e-01, -3.64042788e-01, -6.67930067e-01],
       [-2.31879620e+00,  1.88375784e+00, -3.44289149e-01],
       [ 2.36913679e+00,  1.66728394e+00, -1.04175280e+00],
       [ 1.00781042e+00, -8.32844326e-01, -2.17822510e+00],
       [-1.38666036e+00, -6.60274146e-01, -8.94136968e-01],
       [ 1.17802072e+00,  6.66227596e-01, -8.13471805e-01],
       [ 4.19385105e-01, -1.20813267e+00,  4.37918132e-01],
       [ 2.97421691e+00,  1.66058001e+00, -1.05060936e+00],
       [-7.64158195e-01, -6.42816071e-02,  9.76803256e-01],
       [ 8.07104595e-01, -5.45065735e-01,  3.59461066e-01],
       [ 8.04873211e-01, -1.61057538e+00,  1.20412753e+00],
       [ 1.44346835e+00, -6.47276048e-01, -1.64663478e+00],
       [-1.77589506e+00, -7.04312813e-01, -2.01549801e+00],
       [ 1.05989152e+00, -4.86740388e-01, -7.71890478e-01],
       [-1.86994967e+00,  7.94024378e-01,  7.93930409e-01],
       [-2.31641088e+00,  5.79963784e-01,  5.15886719e-01],
       [ 5.62048218e-01, -1.02308328e+00

In [15]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1])

In [17]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [19]:
X_train.shape, X_test.shape

((300, 3), (700, 3))

In [21]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()

In [23]:
clf

KNeighborsClassifier()

In [25]:
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [27]:
y_pred = clf.predict(X_test)

In [29]:
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
confusion_matrix(y_test, y_pred)

array([[294,  64],
       [ 46, 296]], dtype=int64)

In [33]:
accuracy_score(y_test, y_pred)

0.8428571428571429

In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84       358
           1       0.82      0.87      0.84       342

    accuracy                           0.84       700
   macro avg       0.84      0.84      0.84       700
weighted avg       0.84      0.84      0.84       700



In [37]:
param_grid = {'n_neighbors':[3,5,6,7,10,12,15],
             'algorithm':['ball_tree','brute','kd_tree'],
             'leaf_size':[20,30,40,50]}

In [39]:
param_grid

{'n_neighbors': [3, 5, 6, 7, 10, 12, 15],
 'algorithm': ['ball_tree', 'brute', 'kd_tree'],
 'leaf_size': [20, 30, 40, 50]}

In [43]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=clf, param_grid=param_grid,cv=5, verbose=3)
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'brute', 'kd_tree'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 10, 12, 15]},
             verbose=3)

In [45]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.800 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.850 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.900 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.850 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.867 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.867 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.850 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.917 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.867 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.867 total t

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'brute', 'kd_tree'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 10, 12, 15]},
             verbose=3)

In [47]:
grid.best_params_

{'algorithm': 'ball_tree', 'leaf_size': 20, 'n_neighbors': 5}

In [49]:
grid.best_score_

0.8733333333333334

In [51]:
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

In [53]:
accuracy_score(y_test,y_pred)

0.8428571428571429

In [57]:
#knn as misisng value treatment

import numpy as np
from sklearn.impute import KNNImputer
X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]

In [59]:
X

[[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]

In [61]:
imputer= KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])