# 1. What is a Python library? Why do we use Python libraries?

Answer:

Python Library:  
A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and more convenient for the programmer. As we don’t need to write the same code again and again for different programs. Python libraries play a very vital role in the fields of Machine Learning, Data Science, Data Visualization, etc.

Use Of Python Library: 

1. For the easy maintenance of the code.
2. We split the code into different parts and we can use that code later whenever we need it.
3. Code reusability.


# 2. What is the difference between the Numpy array and List?
Difference b/w Numpy Array and List:

List: 
- List is a data structure that is used in Python. 
- List is a mutable data structure.
- List can be either homogeneous or heterogeneous
- A Python list's versatility makes it an optimal alternative to an array

Numpy Array: 
- All of the elements in the array a homogeneous.
- Size will be fixed into the array.
- Numpy array is used for mathematical calculation.


# 3. Find the shape, size and dimensions of the following array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [2]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]    # List assign to a variable

In [3]:
print(List)     # Print the List

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [4]:
import numpy as np        # Import NumPy as np from numpy library

In [5]:
Arr = np.array(List)    # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
np.shape(Arr)       # Shape of Array

(3, 4)

In [7]:
np.size(Arr)       # Size Of Array

12

In [8]:
np.ndim(Arr)      # Dimension of Array

2

# 4. Writer a python code to access first row of the following array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [9]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]       # List assign to a variable
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [14]:
Arr = np.array(List)         # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# We can access any element from array using index.
# Here I access first row from the array below
Arr[0]     


array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given array?
[[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [16]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]       # List assign to a variable
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [17]:
Arr = np.array(List)         # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
Arr[2,3]     # Accessing array element from third row  and fourth column

12

# 6. Write a code to extract all odd indexed element from the given NumPy Array?
[[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [27]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]       # List assign to a variable
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [28]:
Arr = np.array(List)         # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
Arr[0:3,0:3:2]     # Access all odd indexed element from the NumPy Array

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])