# 1. What is a Python library? Why do we use Python libraries?

Answer:

Python Library:  
A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and more convenient for the programmer. As we don’t need to write the same code again and again for different programs. Python libraries play a very vital role in the fields of Machine Learning, Data Science, Data Visualization, etc.

Use Of Python Library: 

1. For the easy maintenance of the code.
2. We split the code into different parts and we can use that code later whenever we need it.
3. Code reusability.


# 2. What is the difference between the Numpy array and List?
Difference b/w Numpy Array and List:

List: 
- List is a data structure that is used in Python. 
- List is a mutable data structure.
- List can be either homogeneous or heterogeneous
- A Python list's versatility makes it an optimal alternative to an array

Numpy Array: 
- All of the elements in the array a homogeneous.
- Size will be fixed into the array.
- Numpy array is used for mathematical calculation.


# 3. Find the shape, size and dimensions of the following array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [2]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]    # List assign to a variable

In [3]:
print(List)     # Print the List

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [2]:
import numpy as np        # Import NumPy as np from numpy library

In [4]:
Arr = np.array(List)    # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
np.shape(Arr)       # Shape of Array

(3, 4)

In [6]:
np.size(Arr)       # Size Of Array

12

In [7]:
np.ndim(Arr)      # Dimension of Array

2

# 4. Writer a python code to access first row of the following array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [8]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]       # List assign to a variable
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [9]:
Arr = np.array(List)         # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# We can access any element from array using index.
# Here I access first row from the array below
Arr[0]     


array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given array?
[[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [11]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]       # List assign to a variable
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [12]:
Arr = np.array(List)         # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
Arr[2,3]     # Accessing array element from third row  and fourth column

12

# 6. Write a code to extract all odd indexed element from the given NumPy Array?
[[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [14]:
List = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]       # List assign to a variable
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [15]:
Arr = np.array(List)         # Converting list into the NumPy Array
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
Arr[0:3,0:3:2]     # Access all odd indexed element from the NumPy Array

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

Explaination: 
    - We have cretaed a variable name List to store given list, and the print the List variable.
    - Again we have created a variable named as Arr to store array, and also print Arr result. 
    - In the last step we have created the logic to find the all odd elemnt from the Arrar.
      Arr[0:3,0:3:2] 

# 7. How can you generate a random 3x3 matrix with values between 0's and 1's.

In [76]:
Arr = np.random.random((3,3))     # random mothod is used to generate random number
print("Random number between 0's and 1's")

print("\n", Arr)


Random number between 0's and 1's

 [[0.59663991 0.53862019 0.4415045 ]
 [0.66584325 0.7591779  0.78238142]
 [0.41261386 0.85028889 0.44263721]]


# 8. Describe the difference between np.random.rand and np.random.randn?

In [103]:
A = np.random.rand(3,3)
print(A)

[[0.18092334 0.60290385 0.66154669]
 [0.14215629 0.42359444 0.87261025]
 [0.18384494 0.39124213 0.3855874 ]]


In [104]:
B = np.random.randn(3,3)
print(B)

[[-0.09001226 -0.62266808 -0.44395586]
 [ 0.82657168  0.07641651  0.51889059]
 [ 0.14649043 -0.1715755   0.29663788]]


# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [132]:
L = [[1, 2, 3, 4],[5,6,7,8],[9,10,11,12]]
print(L)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [133]:
Arr = np.array(L)
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
np.shape(Arr)

(3, 4)

In [136]:
Arr1 = np.expand_dims(Arr, axis = 1)       # Using np.expand_dims() method we can increase dimention or axis by one at time.
print(Arr1)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

Note: Transpose Matrix: The transpose of a matrix is found by interchanging its rows into columns or columns into rows.



In [139]:
List = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
print(List)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [141]:
Arr = np.array(List)
print(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [143]:
# To transpose the matrix we used np.tranform()method
Arr1 = np.transpose(Arr)       
print(Arr1)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# 11. Consider the following matrix:
Matrix A2 = [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 = [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
1. Index wise multiplication
2. Matrix Multiplication
3. Add both the matrix
4. Suntract matrix B from A
5. Divide matrix B by A

In [151]:
A2 = [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]
B2 = [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]

# Converting the list into the Numpy Array
Arr1 = np.array(A2)
Arr2 = np.array(B2)

In [156]:
# 1. Index wise multiplication
# For index wise multiplication we should use np.multipy() method
C2 = np.multiply(Arr1, Arr2)
print(C2)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [155]:
# 2. Matrix Multiplication
Arr1*Arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [152]:
# 3.Add both the matrix:
print(Arr1+Arr2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [153]:
# 4. Suntract matrix B from A
print(Arr2-Arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [154]:
# 5. Divide matrix B by A
Arr2/Arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be used to swap the byte order of an array?

- numpy.ndarray.byteswap() function is used in Numpy to swap the byte order of an array.

numpy.ndarray.byteswap() function:
numpy.ndarray.byteswap() function toggle between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place. Arrays of byte-strings are not swapped. The real and imaginary parts of a complex number are swapped individually.

Parameters:
inplacebool, optional
If True, swap bytes in-place, default is False.

Returns:
outndarray
The byteswapped array. If inplace is True, this is a view to self.

Example: 

In [15]:
A = np.array([1, 256, 8755], dtype=np.int16)
A

array([   1,  256, 8755], dtype=int16)

In [16]:
A.byteswap(inplace=True)

array([  256,     1, 13090], dtype=int16)

In [9]:
#Arrays of byte-strings are not swapped
A = np.array([b'ceg', b'fac'])
A.byteswap()

array([b'ceg', b'fac'], dtype='|S3')

# 13. What is the significance of the np.linalg.inv function?

The function numpy.linalg.inv() is available in the NumPy module and is used to compute the inverse matrix in Python.

In [36]:
# Taking a 3 * 3 matrix
A = np.array([[1,2,3],[5,6,7],[9,10,11]])

In [37]:
A

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [38]:
# Calculating the inverse of the matrix
np.linalg.inv(A)

array([[-1.93011413e+15,  3.86022825e+15, -1.93011413e+15],
       [ 3.86022825e+15, -7.72045650e+15,  3.86022825e+15],
       [-1.93011413e+15,  3.86022825e+15, -1.93011413e+15]])

# 14. What does the np.reshape function do, and how is it used?

The numpy.reshape() function shapes an array without changing the data of the array.

In [41]:
# Creating an array using np.arange() function
Arr = np.arange(10)
Arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# Shape array with 2 rows and 5 columns
Arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
# shape array with 5 rows and 2 columns
Arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
# shape array with 10 rows and 1 columns
Arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# 15. What is broadcasting in Numpy?


The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

# General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when,
1. they are equal, or
2. one of them is 1.

If these conditions are not met, a "ValueError: operands could not be broadcast together" exception is thrown, indicating that the arrays have incompatible shapes.

Input arrays do not need to have the same number of dimensions. The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions, where the size of each dimension is the largest size of the corresponding dimension among the input arrays. Note that missing dimensions are assumed to have size one.

In [60]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

In [61]:
b = np.array([1.0, 2.0, 3.0])

In [62]:
a + b   # Broadcasting two arrays

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

Note: A one dimensional array added to a two dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

In [65]:
b = np.array([1.0, 2.0, 3.0, 4.0])

In [66]:
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

Note: A one dimensional array added to a two dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.